export const GENERATOR_URL = 'https://generator.musicorumapp.com'
// export const GENERATOR_URL = 'http://localhost:5000'
export const API_URL = 'https://api.musicorumapp.com'
export const UPLOAD_URL = 'https://api.musc.pw'
// export const API_URL = 'http://localhost:4500'
